image: python:3.11.5

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - .env/

test:
  services:
    - name: selenium/standalone-chrome:116.0

  before_script:
    - python -m venv .env
    - source .env/bin/activate
    - python build.py --install

  script:
    - python build.py --lint
    - export SERVER_IP=$(cat /etc/hosts | grep "$(hostname)$" | awk '{print $1}')
    - cat /etc/hosts
    - echo "SERVER_IP is ${SERVER_IP}"
    - python build.py --run-tests-ci

  artifacts:
    reports:
        junit: test_reports.xml
        coverage_report:
          coverage_format: cobertura
          path: coverage_report.xml
