image: python:3.13.2

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - .env/

test:
  services:
    - name: selenium/standalone-chrome:133.0-20250505

  before_script:
    - python -m venv .env
    - source .env/bin/activate
    - python build.py --install

  script:
    - python build.py --lint
    - export SERVER_IP=$(cat /etc/hosts | grep "$(hostname)$" | head -n 1 | awk '{print $1}')
    - cat /etc/hosts
    - echo "SERVER_IP is ${SERVER_IP}"
    - python build.py --run-tests-ci

  artifacts:
    paths:
      - test_reports.xml
      - coverage_report.xml
    reports:
        junit: test_reports.xml
        coverage_report:
          coverage_format: cobertura
          path: coverage_report.xml

  # Regex to search the job log for the pytest-cov coverage result
  coverage: '/TOTAL +[1-9]+ + [1-9]+ +([1-9]+\%)$/'
